use_frameworks!

platform :ios, '10.0'

target 'linkid_mmp_Example' do
  pod 'linkid_mmp', :path => '../'
  pod 'SnapKit', '~> 5.6.0'

  target 'linkid_mmp_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 9.4.0'
  end
end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
  end
 end
end
